base_station/api/urls.py
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

from base_station.events.api.views import LocationViewSet, EventViewSet, OccurrenceViewSet, UpcomingView


router = DefaultRouter()


# Event endpoints
router.register(r'locations', LocationViewSet, base_name='location')
router.register(r'events', EventViewSet, base_name='event')
router.register(r'occurrences', OccurrenceViewSet, base_name='occurrence')


urlpatterns = router.urls


urlpatterns += (
    url(r'^upcoming/$', UpcomingView.as_view(), name='upcoming'),
)

base_station/events/urls.py
from django.conf.urls import url

from events.views import (
    EventDetailViewBase, UpcomingOccurrencesViewBase,
    OccurrenceDetailViewBase, OccurrenceUpdateViewBase, OccurrenceDeleteViewBase)


urlpatterns = (
    url(r'upcoming$', UpcomingOccurrencesViewBase.as_view(), name='upcoming'),
    # occurrence views
    url(r'^(?P<pk>\d+)/$',
        EventDetailViewBase.as_view(),
        name='detail'),
    url(r'^(?P<pk>\d+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',
        OccurrenceDetailViewBase.as_view(),
        name='occurrence_detail'),
    url(r'^(?P<pk>\d+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/update/$',
        OccurrenceUpdateViewBase.as_view(),
        name='occurrence_update'),
    url(r'^(?P<pk>\d+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/delete/$',
        OccurrenceDeleteViewBase.as_view(),
        name='occurrence_delete'),
)

base_station/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.decorators.csrf import csrf_exempt

from base_station.races.schema import schema
from graphene.contrib.django.views import GraphQLView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='root.html'), name="home"),
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("base_station.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # API
    url(r'^api/', include("base_station.api.urls", namespace="api")),

    # Graphql urls
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(schema=schema))),
    url(r'^graphiql', include('django_graphiql.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permissin Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

base_station/events/models.py
from django.db import models
from django_extensions.db.models import (
    TitleSlugDescriptionModel,
    TimeStampedModel
)
from simple_history.models import HistoricalRecords


from base_station.utils.models import UUIDModel


class EventTemplate(UUIDModel, TitleSlugDescriptionModel, TimeStampedModel):
    """
    Dictates the logic that is used when running a race.
    """
    history = HistoricalRecords()

    def __str__(self):
        return self.title


# Should models that are related to event design be included in the models here?

# Timer model to hold different designated times to trigger an esettings

class Event(UUIDModel, TitleSlugDescriptionModel, TimeStampedModel):

    template = models.ForeignKey(EventTemplate)

    history = HistoricalRecords()

    def __str__(self):
        return self.title

base_station/events/models/managers.py
from datetime import timedelta

from django.db import models
from django.db.models import Q


class EventModelManager(models.Manager):
    """Custom manager for the ``Event`` model class."""

    def get_occurrences(self, start, end, category=None):
        """Return a list of events and occurrences for the given period."""
        # we always want the time of start and end to be at 00:00
        start = start.replace(minute=0, hour=0)
        end = end.replace(minute=0, hour=0)
        # if we recieve the date of one day as start and end, we need to set
        # end one day forward
        if start == end:
            end = start + timedelta(days=1)
        # retrieving relevant events
        # TODO currently for events with a rule, I can't properly find out when
        # the last occurrence of the event ends, or find a way to filter that,
        # so I'm still fetching **all** events before this period, that have a
        # end_recurring_period.
        # For events without a rule, I fetch only the relevant ones.

        qs = self.get_queryset().filter(start__lt=end)

        # if category:
        #     qs = qs.filter(Q(category=category) | Q(category__parent=category))
        #     
        # get all occurrences for those events that don't already have a
        # persistent match and that lie in this period.
        all_occurrences = []
        for event in qs:
            all_occurrences.extend(event.get_occurrences(start, end))

        # sort and return
        return sorted(all_occurrences, key=lambda x: x.start)

base_station/events/models/meta.py
# -*- coding: utf-8 -*-
from hashlib import md5

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.postgres.fields import JSONField
from django.utils.translation import ugettext_lazy as _

from base_station.utils.geo import geocode


class Location(models.Model):
    """Geo and meta representation of a location"""

    name = models.CharField(
        _('Location Name'),
        max_length=255
    )

    address = models.CharField(
        _('Address'),
        max_length=255,
        blank=True,
        null=True,
        unique=True
    )

    location = models.PointField(
        _('Location'),
        blank=True,
        null=True
    )

    location_hash = models.CharField(
        max_length=32,
        null=True
    )

    meta = JSONField(
        _('metadata'),
        blank=True,
        null=True
    )

    objects = models.GeoManager()

    def __str__(self):
        return "{name}".format(name=self.name)

    def save(self, **kwargs):
        location_hash = md5(
            '{}@{}'.format(self.name, self.address).encode('utf-8')).hexdigest()
        if self.location_hash != location_hash and self.address:
            location_geocode = geocode(self.address)
            if location_geocode:
                self.meta = location_geocode.raw
                pos = [float(self.meta.get(coord)) for coord in ['lon', 'lat']]
                self.location = Point(*pos)
                self.location_hash = location_hash
            else:
                self.meta = {"geocoded": False}
                self.location = None
        super().save(**kwargs)

base_station/events/models/templates.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import (
    AutoSlugField
)
from django_extensions.db.models import (
    TitleSlugDescriptionModel,
    TimeStampedModel
)
from simple_history.models import HistoricalRecords


from base_station.utils.models import SyncModel


class EventTemplate(SyncModel, TimeStampedModel):
    """
    Dictates the logic that is used when running a race.
    TODO: these become race rules, events are containers for races. Races contain specific rule sets for their operation.
    # TODO: delete
    """

    name = models.CharField(_("name"), max_length=255, default="")
    slug = AutoSlugField(_("slug"), populate_from="name")
    creator = models.ForeignKey("users.User", blank=True, null=True)
    # May have to store creator details in non FK way due to future sync issues?

    history = HistoricalRecords()

    def __str__(self):
        return self.name


class Timer(SyncModel):
    """
    Timer model to hold different designated times to trigger events
    """

    name = models.CharField(_("name"), max_length=255)
    slug = AutoSlugField(_("slug"), populate_from="name")
    duration = models.DurationField()
    tempalte = models.ForeignKey(EventTemplate)

    history = HistoricalRecords()


# class

base_station/events/models/utils.py
class OccurrenceReplacer(object):
    """
    Replace missing occurrences in a date rage.

    When getting a list of occurrences, the last thing that needs to be done
    before passing it forward is to make sure all of the occurrences that
    have been stored in the datebase replace, in the list you are returning,
    the generated ones that are equivalent. This class makes this easier.
    """

    def __init__(self, persisted_occurrences):
        lookup = [
            ((occurrence.event, occurrence.original_start, occurrence.original_end), occurrence) for
            occurrence in persisted_occurrences]
        self.lookup = dict(lookup)

    def get_occurrence(self, occurrence):
        """
        Return a persisted occurrences matching the occurrence

        Returned occurrence will be removed from future lookup as it's been matched
        """
        return self.lookup.pop(
            (occurrence.event, occurrence.original_start, occurrence.original_end),
            occurrence)

    def has_occurrence(self, occurrence):
        return (occurrence.event, occurrence.original_start, occurrence.original_end) in self.lookup

    def get_additional_occurrences(self, start, end):
        """Return persisted occurrences which are now in the period"""
        occurrences = []
        for key, occurrence in self.lookup.items():
            if (end and occurrence.start < end) and occurrence.end >= start and not occurrence.cancelled:
                occurrences.append(occurrence)
        return occurrences

base_station/pilots/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from base_station.utils.models import SyncModel
from base_station.users.models import User


class Pilot(SyncModel):
    """Store details related to a pilot"""

    callsign = models.CharField(_('Moniker/Callsign'), blank=True, max_length=100)
    # optional relationship to a user
    user = models.ForeignKey(User, blank=True, null=True)

    def __str__(self):
        if self.user:
            return "{} ({})".format(self.callsign, (self.user.name or self.user))
        return "{}".format(self.callsign)

base_station/utils/models.py
import uuid

from django.db import models


class SyncModel(models.Model):
    """
    A model that can be synced between the base station and the sync web service
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True

base_station/events/api/views.py
from django.utils.timezone import now, timedelta
from rest_framework import viewsets, generics
from rest_framework.response import Response
from rest_framework_gis.pagination import GeoJsonPagination

from .serializers import GeoLocationSerializer, EventSerializer, GeoOccurrenceSerializer
from base_station.events.models import Location, Event, Occurrence


class LocationViewSet(viewsets.ModelViewSet):
    queryset = Location.objects.all()
    pagination_class = GeoJsonPagination
    serializer_class = GeoLocationSerializer


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer


class OccurrenceViewSet(viewsets.ModelViewSet):
    queryset = Occurrence.objects.all()
    pagination_class = GeoJsonPagination
    serializer_class = GeoOccurrenceSerializer


class UpcomingView(generics.GenericAPIView):
    serializer_class = GeoOccurrenceSerializer

    # authentication_classes
    permission_classes = ()

    def get(self, *args, **kwargs):
        qs_kwargs = {
            'start': now(),
            'end': now() + timedelta(40)
        }
        occurrences = Event.objects.get_occurrences(**qs_kwargs)
        serializer = self.get_serializer(occurrences, many=True)
        return Response(serializer.data)

base_station/events/views/admin.py
"""User admin views for the models of the ``events`` app."""

base_station/events/views/base.py
from django.core.urlresolvers import reverse
from django.forms.models import model_to_dict
from django.http import Http404, HttpResponseRedirect
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from django.utils.timezone import datetime, now, timedelta

from events.models import Event, Occurrence


class UpcomingOccurrencesViewBase(ListView):
    context_object_name = 'occurrences'

    def get_queryset(self):
        qs_kwargs = {
            'start': now(),
            'end': now() + timedelta(40)
        }
        return Event.objects.get_occurrences(**qs_kwargs)


class EventsListViewBase(ListView):
    context_object_name = 'events'
    model = Event


class EventMixin(object):
    model = Event
    context_object_name = 'event'


class EventDetailViewBase(EventMixin, DetailView):
    """View to return information of an event."""


class EventCreateViewBase(EventMixin, CreateView):
    pass


class EventUpdateViewBase(EventMixin, UpdateView):
    pass


class EventDeleteViewBase(EventMixin, DeleteView):
    pass


class OccurrenceViewMixin(object):
    """Mixin to avoid repeating code for the Occurrence view classes."""
    # form_class = OccurrenceForm

    def dispatch(self, request, *args, **kwargs):
        try:
            self.event = Event.objects.get(pk=kwargs.get('pk'))
        except Event.DoesNotExist:
            raise Http404
        year = int(kwargs.get('year'))
        month = int(kwargs.get('month'))
        day = int(kwargs.get('day'))
        try:
            date = datetime(year, month, day)
        except (TypeError, ValueError):
            raise Http404('not a valid occurrence date')
        # this should retrieve the one single occurrence, that has a
        # matching start date
        try:
            occ = Occurrence.objects.get(
                start__year=year, start__month=month, start__day=day)
        except Occurrence.DoesNotExist:
            # TODO: Change start date to equal that being searched for so we
            # find it quicker with less generator iteration
            occ_gen = self.event.get_occurrences(date)
            occ = next(occ_gen)
            while occ.start.date() < date.date():
                occ = next(occ_gen)
        if occ.start.date() == date.date():
            self.occurrence = occ
        else:
            raise Http404('no found occurrence for this date')
        self.object = occ
        return super(OccurrenceViewMixin, self).dispatch(
            request, *args, **kwargs)

    def get_object(self):
        return self.object

    def get_form_kwargs(self):
        kwargs = super(OccurrenceViewMixin, self).get_form_kwargs()
        kwargs.update({'initial': model_to_dict(self.object)})
        return kwargs


class OccurrenceDeleteViewBase(OccurrenceViewMixin, DeleteView):
    """View to delete an occurrence of an event."""
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        decision = self.request.POST.get('decision')
        self.object.delete_period(decision)
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, object):
        ctx = super(OccurrenceDeleteViewBase, self).get_context_data()
        ctx.update({
            # 'decisions': OCCURRENCE_DECISIONS,
            'object': self.object
        })
        return ctx

    def get_success_url(self):
        return reverse('events:current_month')


class OccurrenceDetailViewBase(OccurrenceViewMixin, DetailView):
    """View to show information of an occurrence of an event."""
    pass


class OccurrenceUpdateViewBase(OccurrenceViewMixin, UpdateView):
    """View to edit an occurrence of an event."""
    pass

base_station/races/views.py
from django.shortcuts import render

# Create your views here.

base_station/trackers/views.py
from django.shortcuts import render

# Create your views here.

base_station/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Base Station{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">Base Station</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

      <!-- Tether - a requirement for Bootstrap tooltips -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.1.1/js/tether.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>

base_station/templates/root.html
{% load render_bundle from webpack_loader %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Base Station{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div id="root">
    </div>
    {% if debug %}
    <script type="text/javascript" src="/bundle.js"> </script>
    {% else %}
    {% render_bundle 'bundle' %}
    {% endif %}
  </body>
</html>